// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/joke.ts";
import * as $1 from "./routes/index.tsx";
import * as $$0 from "./islands/AddContact.tsx";
import * as $$1 from "./islands/Contact.tsx";
import * as $$2 from "./islands/ContactList.tsx";
import * as $$3 from "./islands/Search.tsx";

const manifest = {
  routes: {
    "./routes/api/joke.ts": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/AddContact.tsx": $$0,
    "./islands/Contact.tsx": $$1,
    "./islands/ContactList.tsx": $$2,
    "./islands/Search.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
